//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalariesPract19
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentHandbook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentHandbook()
        {
            this.StructuralEnterprises = new HashSet<StructuralEnterprise>();
        }
    
        public int Department { get; set; }
        public string NameOfDepartment { get; set; }
        public string Head { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructuralEnterprise> StructuralEnterprises { get; set; }
    }
}
