//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalariesPract19
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalariesPr19Entities : DbContext
    {
        public SalariesPr19Entities()
            : base("name=SalariesPr19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentHandbook> DepartmentHandbooks { get; set; }
        public virtual DbSet<SalaryHandbook> SalaryHandbooks { get; set; }
        public virtual DbSet<StaffingTable> StaffingTables { get; set; }
        public virtual DbSet<StructuralEnterprise> StructuralEnterprises { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeWorkedTimeSheetSheet> TimeWorkedTimeSheetSheets { get; set; }
    }
}
