//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalariesPract19
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffingTable
    {
        public int TimeSheetNumber { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public Nullable<int> Department { get; set; }
    
        public virtual SalaryHandbook SalaryHandbook { get; set; }
    }
}
