//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalariesPract19
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeWorkedTimeSheetSheet
    {
        public int TimeSheetNumber { get; set; }
        public Nullable<int> TimeWorkedInDays { get; set; }
        public Nullable<int> NumberOfMonth { get; set; }
    }
}
